-- 华云智联官网 V2.0 初始表结构（H2 PostgreSQL 模式与 PostgreSQL 通用）
-- 设计依据：design_document/K-05 §3；内容采用“文档型内容表”，见 website/docs/adr/0002-content-document-table.md

CREATE TABLE content_item (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_type VARCHAR(32)   NOT NULL,
    slug         VARCHAR(160)  NOT NULL,
    locale       VARCHAR(8)    NOT NULL DEFAULT 'zh',
    status       VARCHAR(16)   NOT NULL DEFAULT 'published',
    title        VARCHAR(400)  NOT NULL,
    summary      VARCHAR(4000),
    category     VARCHAR(64),
    sort_order   INT           NOT NULL DEFAULT 0,
    featured     BOOLEAN       NOT NULL DEFAULT FALSE,
    published_at DATE,
    expires_at   DATE,
    authorized   BOOLEAN       NOT NULL DEFAULT TRUE,
    archived     BOOLEAN       NOT NULL DEFAULT FALSE,
    body_json    TEXT          NOT NULL,
    updated_at   TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_content_item UNIQUE (content_type, slug, locale)
);
CREATE INDEX idx_content_type_sort ON content_item (content_type, status, sort_order);

CREATE TABLE content_meta (
    meta_key   VARCHAR(64)  PRIMARY KEY,
    meta_value VARCHAR(255) NOT NULL
);

CREATE TABLE leads (
    id               VARCHAR(36)   PRIMARY KEY,
    lead_type        VARCHAR(16)   NOT NULL,
    name             VARCHAR(50)   NOT NULL,
    company          VARCHAR(100)  NOT NULL,
    job_title        VARCHAR(50),
    phone_enc        VARCHAR(200),
    phone_hash       VARCHAR(64),
    email_enc        VARCHAR(400),
    email_hash       VARCHAR(64),
    product_interest VARCHAR(100),
    scenario         VARCHAR(2000),
    locale           VARCHAR(8)    NOT NULL DEFAULT 'zh',
    source_page      VARCHAR(255),
    utm_source       VARCHAR(100),
    utm_medium       VARCHAR(100),
    utm_campaign     VARCHAR(100),
    ip_hash          VARCHAR(64),
    consent_version  VARCHAR(20)   NOT NULL,
    consent_at       TIMESTAMP     NOT NULL,
    status           VARCHAR(16)   NOT NULL DEFAULT 'new',
    notes            VARCHAR(2000),
    created_at       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_leads_created ON leads (created_at);
CREATE INDEX idx_leads_status ON leads (status, created_at);
CREATE INDEX idx_leads_phone ON leads (phone_hash, created_at);
CREATE INDEX idx_leads_email ON leads (email_hash, created_at);

CREATE TABLE audit_logs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor       VARCHAR(64)   NOT NULL,
    action      VARCHAR(32)   NOT NULL,
    target_type VARCHAR(32)   NOT NULL,
    target_id   VARCHAR(64)   NOT NULL,
    detail      VARCHAR(1000),
    created_at  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_audit_target ON audit_logs (target_type, target_id);

CREATE TABLE rum_metrics (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metric       VARCHAR(8)       NOT NULL,
    metric_value DOUBLE PRECISION NOT NULL,
    rating       VARCHAR(20),
    page_path    VARCHAR(255),
    device       VARCHAR(16),
    created_at   TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_rum_created ON rum_metrics (created_at);
